### ISSUE TITLE
Sass files not working?

### ISSUE THREAD

**Issue by timothywilkins** [teamscops/bulmapress#16]
I just started working with bulmapress and I think it's really cool!! I am having an issue with the Sass files however. I want to change some of the default styling of the theme, more than just adding bulma classes in the PHP files. I discovered the Sass files and thought to myself I found the jackpot, but anytime I change/add a styling rule nothing happens to my site. For instance, I would change the primary color from turquoise to yellow in the override file but the page would still be turquoise. Is bulmapress meant to have the Sass edited, or am I going about this all wrong?

**Comment by paulovsky** [comment]
Make sure your header.php is linking to your css created file, and not Bulma's CDN. Otherwise try to look into your code using your browser's inspector.

**Comment by CMzKonsult** [comment]
> Make sure your header.php is linking to your css created file, and not Bulma's CDN. Otherwise try to look into your code using your browser's inspector.

Need to borrow this thread though I can't get this to work. Do you mean that I should remove <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.1/css/bulma.min.css" /> from my header? 

I'll break my head soon

**Comment by eeegor** [comment]
@CMzKonsult were you able to resolve your issue?

Just remove this line from the `./header.php` and the local version should be picked up automatically
```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.1/css/bulma.min.css" />
```

The local script is enqueued in `./function/scripts-styles.php`
```php
wp_enqueue_style( 'bulmapress-bulma-style', get_template_directory_uri() . '/frontend/bulmapress/css/bulmapress.css' );
```

In order to generate a new version of the local `css` you'll need to build the `scss` files with `npm` or `yarn`

1. Make sure you have `node.js` and `yarn` or `npm` on your environment
2. Inside `./frontend/bulmapress/` run `yarn` or `npm install`
3. Modify `scss` files
4. Inside `./frontend/bulmapress/package.json` you'll find the `scripts` section for available options
5. Run `yarn build` or `npm run build`
6. New `css` will be generated and the `node_modules` folder removed
