### ISSUE TITLE
UPDATE to bulma 0.61 ?

### ISSUE THREAD

**Issue by tweed** [teamscops/bulmapress#8]
THRILLED TO FIND THIS - thank you

CAN WE just update to bulma 0.61 ???
best practices?

I hope this is the way to go to use bulma in wordpress

Sure does feel and look terrific!!

updates pending?

whatever happens thank you!!

is the wp-bootstrap-navwalker necessary?
why not bulma nav ?

**Comment by raygervais** [comment]
@tweed, it appears that this project hasn't been updated since the initial commit. 
I plan on updating and doing a pull request from here: https://github.com/raygervais/bulmapress, will fork and keep as my own if this project has been abandoned. Can you confirm @teamscops if this project is still active?

**Comment by raygervais** [comment]
Actually @tweed, I see @petrvalek is already ahead of what I was thinking, and it would be better for us to contribute to his repo if that is desired instead of reproducing the same efforts again. https://github.com/petrvalek/bulmapress

Opinions?

**Comment by raygervais** [comment]
Deleted previous comment due to some issues still present in implementation, reverting back to my original comment ^
